export type CatalogOffer={id:string;partition:"general";regionId:string;area:string;productId:string;name:string;category:string;identifier:{type:"jan"|"isbn"|"vehicle"|"model";value:string;namespace:string};price:number;availability:"in_stock"|"low_stock"|"reservation";observedAt:string;sourceType:"merchant"|"pos_csv"|"user_report";confidence:number;crowdScore:number};
export const catalog:CatalogOffer[]=[
{id:"of-1",partition:"general",regionId:"12106",area:"千葉市美浜区",productId:"p-1",name:"モバイルバッテリー 10000mAh",category:"防災・推し活",identifier:{type:"jan",value:"4902430906265",namespace:"SAMPLE"},price:3480,availability:"in_stock",observedAt:"2026-07-20T06:50:00+09:00",sourceType:"pos_csv",confidence:92,crowdScore:18},
{id:"of-2",partition:"general",regionId:"13104",area:"新宿区",productId:"p-2",name:"はじめてのAI仕事術",category:"書籍",identifier:{type:"isbn",value:"9784295017844",namespace:"ISBN"},price:1980,availability:"low_stock",observedAt:"2026-07-20T05:20:00+09:00",sourceType:"merchant",confidence:88,crowdScore:42},
{id:"of-3",partition:"general",regionId:"14109",area:"横浜市港北区",productId:"p-3",name:"プリウス60系対応ドライブレコーダー",category:"車・カー用品",identifier:{type:"vehicle",value:"6AA-ZVW60",namespace:"TOYOTA"},price:19800,availability:"reservation",observedAt:"2026-07-19T18:00:00+09:00",sourceType:"merchant",confidence:84,crowdScore:61},
{id:"of-4",partition:"general",regionId:"27127",area:"大阪市北区",productId:"p-4",name:"高浸透ナノケア ドライヤー",category:"家電・美容",identifier:{type:"model",value:"EH-NA0J",namespace:"PANASONIC"},price:34650,availability:"in_stock",observedAt:"2026-07-18T14:30:00+09:00",sourceType:"user_report",confidence:57,crowdScore:47}];
export const labels={jan:"JAN",isbn:"ISBN",vehicle:"車種",model:"品番",in_stock:"在庫あり",low_stock:"残りわずか",reservation:"取付予約可"}as const;
export function searchCatalog(area:string,query:string){const a=area.trim().toLowerCase(),q=query.trim().toLowerCase();return catalog.filter(x=>x.partition==="general"&&(!a||x.area.toLowerCase().includes(a))&&(!q||`${x.identifier.value}${x.name}${x.category}`.toLowerCase().includes(q)))}
export function freshness(observedAt:string){const hours=Math.max(0,(Date.now()-new Date(observedAt).getTime())/36e5);return hours<6?"最新":hours<48?"確認済み":"要再確認"}
export function formatObservedAt(value:string){return new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
