"use client";
import{FormEvent,useMemo,useState}from"react";import"./compass.css";
const purposes=["韓国・台湾旅行","コスメ購入","映像・電子書籍","VR機器","推し活イベント"] as const;type Purpose=typeof purposes[number];
const baseItems:Record<Purpose,string[]>={"韓国・台湾旅行":["パスポート有効期限を確認","航空券とホテルのキャンセル条件を保存","eSIMまたはWi-Fiを準備","変換プラグと充電器を準備","海外旅行保険を確認"],"コスメ購入":["肌悩みと避けたい成分を整理","内容量あたりの価格を比較","返品条件を確認","在庫・値下げ通知を設定"],"映像・電子書籍":["見放題・レンタル・購入を比較","配信終了日を確認","無料期間後の料金を確認","作品通知を設定"],"VR機器":["作品の180°/360°・2D/3Dを確認","機器の対応解像度を確認","PC要件と端子を確認","返品条件と保証を確認"],"推し活イベント":["公式販売元を確認","本人確認書類を準備","会場までの交通と終電を確認","イベント変更通知を設定"]};
export default function Home(){const[purpose,setPurpose]=useState<Purpose>("韓国・台湾旅行"),[pace,setPace]=useState("失敗を避けたい"),[budget,setBudget]=useState("標準"),[generated,setGenerated]=useState(false),[checked,setChecked]=useState<string[]>([]),[email,setEmail]=useState(""),[consent,setConsent]=useState(false),[message,setMessage]=useState("");const items=useMemo(()=>[...baseItems[purpose],...(pace==="最短で決めたい"?["比較候補を3つ以内に絞る"]:[]),...(budget==="節約"?["総額と解約条件を優先して比較"]:budget==="品質優先"?["保証・サポート・正規販売元を優先"]:[])],[purpose,pace,budget]);function toggle(item:string){setChecked(now=>now.includes(item)?now.filter(x=>x!==item):[...now,item])}async function save(event:FormEvent){event.preventDefault();try{const response=await fetch("/api/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,purpose,pace,budget,items,checked,consent})});const body=await response.json() as{error?:string};if(!response.ok)throw new Error(body.error||"保存できませんでした");setMessage("チェックリストを保存しました")}catch(error){setMessage(error instanceof Error?error.message:"保存できませんでした")}}
return <main><header><a className="brand" href="#top">Choice<span>Compass</span></a><nav><a href="#diagnosis">好み診断</a><a href="#list">チェックリスト</a><a href="#routes">おすすめサービス</a></nav></header><section className="hero" id="top"><p className="eyebrow">DECIDE WITH CONFIDENCE</p><h1>迷いをほどいて、<br/><em>次にやること</em>を見つける。</h1><p>旅行、推し活、コスメ、作品、VR。好みと予算を答えると、比較の軸と準備チェックリストを自動生成します。</p><a href="#diagnosis">3問で診断する →</a></section>
<section className="diagnosis" id="diagnosis"><div><p className="eyebrow dark">PREFERENCE DIAGNOSIS</p><h2>あなたの選び方を教えてください。</h2><p>回答はおすすめの並びとチェック項目にだけ使います。</p></div><form onSubmit={event=>{event.preventDefault();setGenerated(true);setChecked([]);document.getElementById("list")?.scrollIntoView({behavior:"smooth"})}}><label>何を準備しますか？<select value={purpose} onChange={e=>setPurpose(e.target.value as Purpose)}>{purposes.map(x=><option key={x}>{x}</option>)}</select></label><label>決め方の好み<select value={pace} onChange={e=>setPace(e.target.value)}><option>失敗を避けたい</option><option>最短で決めたい</option><option>じっくり比較したい</option></select></label><label>予算の考え方<select value={budget} onChange={e=>setBudget(e.target.value)}><option>節約</option><option>標準</option><option>品質優先</option></select></label><button>AIチェックリストを作る →</button></form></section>
<section className="result" id="list"><div className="result-head"><div><p className="eyebrow dark">YOUR COMPASS</p><h2>{generated?`${purpose}の準備リスト`:"診断すると、ここにリストができます"}</h2></div>{generated&&<strong>{checked.length}/{items.length}</strong>}</div>{generated?<><div className="profile"><span>{pace}</span><span>予算：{budget}</span><b>おすすめ方針：{budget==="節約"?"総額・解約条件を優先":budget==="品質優先"?"保証と正規性を優先":"価格と安心のバランス"}</b></div><ul className="checklist">{items.map((item,index)=><li className={checked.includes(item)?"done":""} key={item}><button onClick={()=>toggle(item)}><i>{checked.includes(item)?"✓":index+1}</i><span>{item}</span></button></li>)}</ul><form className="save" onSubmit={save}><div><b>このリストを保存</b><span>あとで続きから確認できます。</span></div><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> 保存とプライバシーポリシーに同意</label><button disabled={!consent}>メールに保存 →</button><output>{message}</output></form></>:<a className="empty-cta" href="#diagnosis">好み診断を始める</a>}</section>
<section className="routes" id="routes"><p className="eyebrow">SMART ROUTES</p><h2>準備から、比較・予約へ。</h2><div><article><b>01</b><h3>旅行準備</h3><p>ホテル、航空券、eSIM、Wi-Fi、保険、旅行用品を比較。</p><a href="https://tabijunbi-jp.syunnjack.chatgpt.site">旅行準備を見る →</a></article><article><b>02</b><h3>価格・在庫</h3><p>コスメの単価、成分、在庫、値下げを確認。</p><a href="https://cosmewatch-jp.syunnjack.chatgpt.site">コスメ比較を見る →</a></article><article><b>03</b><h3>作品・機器</h3><p>配信先と視聴機器の対応を確認。</p><a href="https://dokodemiru-jp.syunnjack.chatgpt.site">作品比較を見る →</a></article></div></section><footer><a className="brand" href="#top">Choice<span>Compass</span></a><p>迷いを、行動できるチェックリストへ。</p><small>© 2026 Choice Compass · 提携先リンクには広告が含まれる場合があります。</small></footer></main>}
