"use client";
import{useEffect,useMemo,useState}from"react";import{catalog,formatObservedAt,freshness,labels,searchCatalog,type CatalogOffer}from"./lib/catalog";import"./catalog.css";
type Alert={offerId:string;name:string;condition:"stock_or_price";createdAt:string};
export default function Home(){const[area,setArea]=useState("");const[code,setCode]=useState("");const[searched,setSearched]=useState(false);const[notice,setNotice]=useState<string|null>(null);const[alerts,setAlerts]=useState<Alert[]>([]);useEffect(()=>{try{setAlerts(JSON.parse(localStorage.getItem("choice-compass.alerts")||"[]"))}catch{setAlerts([])}},[]);const results=useMemo(()=>searchCatalog(area,code),[area,code]);const shown=searched?results:catalog;function addAlert(item:CatalogOffer){const next=[...alerts.filter(x=>x.offerId!==item.id),{offerId:item.id,name:item.name,condition:"stock_or_price" as const,createdAt:new Date().toISOString()}];setAlerts(next);localStorage.setItem("choice-compass.alerts",JSON.stringify(next));setNotice(`${item.name}の入荷・値下げ通知を保存しました。`)}return <main>
<header className="site-header"><a className="brand" href="#top"><span>Choice</span> Compass</a><nav aria-label="メインナビゲーション"><a href="#search">商品を探す</a><a href="#how">仕組み</a><button onClick={()=>setNotice(`この端末に${alerts.length}件の通知条件があります。`)}>通知リスト <b>{alerts.length}</b></button></nav></header>
<section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">地域の商品選びを、もっと確かに。</p><h1>その商品、<br/><em>近くで買える。</em></h1><p className="lead">市区町村とJAN・ISBN・車種・品番を組み合わせ、在庫・価格・混み具合・情報鮮度を共通データ形式で比較します。</p><div className="trust-row"><span>✓ 一般商品だけを検索</span><span>✓ 確認日時と信頼度</span><span>✓ 広告を明記</span></div></div><div className="signal-card"><div className="signal-head"><span>千葉市美浜区</span><strong>UPDATED</strong></div><h2>買いやすさ指数</h2><div className="score"><b>82</b><span>/100<br/>比較的すいています</span></div><div className="bars">{[38,55,72,88,63,42,31].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div><p>店舗CSVと混雑シグナルから算出・信頼度92</p></div></section>
<section className="search-panel" id="search"><div><label htmlFor="area">市区町村・駅</label><input id="area" value={area} onChange={e=>setArea(e.target.value)} placeholder="例：新宿区、横浜市"/></div><div><label htmlFor="code">JAN・ISBN・車種・品番</label><input id="code" value={code} onChange={e=>setCode(e.target.value)} placeholder="コードまたは商品名を入力"/></div><button className="primary" onClick={()=>setSearched(true)}>近くの商品を探す →</button></section>
<section className="results" aria-live="polite"><div className="section-title"><div><p className="eyebrow">AFFILIATE FEED CORE</p><h2>{searched?`${results.length}件の候補が見つかりました`:"共通カタログの注目商品"}</h2></div><p>画面設計用サンプルです。購入前に販売店で最新情報をご確認ください。</p></div><div className="card-grid">{shown.map(item=><article className="product-card" key={item.id}><div className="product-top"><span className="kind">{labels[item.identifier.type]}</span><span className={`stock ${item.crowdScore>=50?"busy":""}`}>● {labels[item.availability]}</span></div><h3>{item.name}</h3><code>{item.identifier.value}</code><p className="area">⌖ {item.area}</p><div className="meta-row"><span className={`freshness f-${freshness(item.observedAt)}`}>{freshness(item.observedAt)}</span><span>{formatObservedAt(item.observedAt)}確認</span><span>信頼度 {item.confidence}</span></div><div className="product-bottom"><strong>¥{item.price.toLocaleString()}<small>〜</small></strong><button onClick={()=>addAlert(item)}>{alerts.some(x=>x.offerId===item.id)?"✓ 通知中":"通知する"}</button></div><div className="meter"><span style={{width:`${100-item.crowdScore}%`}}/></div><small>買いやすさ {100-item.crowdScore} ・ 情報源 {item.sourceType}</small></article>)}</div>{searched&&results.length===0&&<div className="empty">一致するデータはありません。地域名またはコードを短くしてお試しください。</div>}</section>
<section className="how" id="how"><p className="eyebrow">SHARED DATA CONTRACT</p><h2>識別・鮮度・通知を、全サイトで共通化。</h2><div className="steps"><article><b>01</b><h3>商品を正確に特定</h3><p>JAN、ISBN、車種型式、メーカー名前空間付き品番で取り違えを防ぎます。</p></article><article><b>02</b><h3>根拠と鮮度を表示</h3><p>店舗・POS・利用者報告ごとに確認日時と信頼度を保持します。</p></article><article><b>03</b><h3>通知条件を保存</h3><p>第一版は端末内へ保存し、次段階で共通通知基盤へ接続します。</p></article></div></section>
<footer><div className="brand"><span>Choice</span> Compass</div><p>一般商品専用の地域型比較サイトです。成人向けデータは検索対象から分離されています。広告リンクを含む場合は「広告」と明記します。</p><nav><a href="#">運営情報</a><a href="#">プライバシー</a><a href="#">広告掲載方針</a></nav></footer>{notice&&<div className="toast" role="status">{notice}<button aria-label="閉じる" onClick={()=>setNotice(null)}>×</button></div>}</main>}
